files:
  - source: /_data/locales/*/en.*
    translation: /%original_path%/%two_letters_code%.%file_extension%
  - source: /docs/en/*.md
    translation: /docs/%two_letters_code%/%original_file_name%
